'use client';

import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';
import { usePathname } from 'next/navigation';

// Uncomment and update metadata for better SEO
// export const metadata = {
//   title: 'My Next.js App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname() ?? '/';

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="min-h-screen relative font-sans">
        <img
          src="/assets/svgs/TopLeftVector.svg"
          alt=""
          height={785}
          width={600}
          className="absolute top-0 left-0 -z-10 pointer-events-none"
        />

        <Navbar currentPath={pathname} />

        <main className="mt-4">{children}</main>

        <Toaster />
      </body>
    </html>
  );
}
