'use client';

import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';
import { usePathname } from 'next/navigation';
import Image from 'next/image';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname() ?? '/';

  return (
    <html lang="en">
      <body>
        <Image
          src={'/assets/svgs/TopLeftVector.svg'}
          alt=""
          height={785}
          width={600}
          className="absolute top-0 left-0 -z-10"
        />
        <Navbar currentPath={pathname} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
